### ISSUE TITLE
finals2000A.all has expired

### ISSUE THREAD

**Issue by 6ruff** [brunobord/skyfield-data#20]
The expiration date for finals2000A.all is 2022-2-13 which is causing the following warning:

`RuntimeWarning: The file finals2000A.all has expired. Please upgrade your version of `skyfield-data` or expect computation errors`

**Comment by brunobord** [comment]
oh boy! thank you for the bug report! This project needs care.

I'll publish a new version ASAP.

**Comment by brunobord** [comment]
Thanks a million for the bug report, I hope you'll have a safe and happy upgrading! Enjoy your v4.0.0!

https://pypi.org/project/skyfield-data/4.0.0/

**Comment by 6ruff** [comment]
Many thanks for the quick turnaround, it works like a dream !

**Comment by ReimarBauer** [comment]
Thanks from Open-MSS team, our upgrade went smoothly.
