### ISSUE TITLE
FIX Circle CI AND Travis builds

### ISSUE THREAD

**Issue by brunobord** [brunobord/skyfield-data#22]
* Circle CI build fails
* Travis CI build doesn't even start.

**Comment by brunobord** [comment]
this is becoming totally silly. Travis CI can't handle my open-source projects because I've got "more users than allowed" and Circle-CI can't build my Python 2.6 stuff.

Considering switching to Github CI.

**Comment by Deuchnord** [comment]
> Considering switching to Github CI.

I'd be happy to make a PR to migrate to GitHub Action, if you want. :slightly_smiling_face:

**Comment by ReimarBauer** [comment]
Hi @brunobord tried to fix the keys problem, not sure if that solves this. 
Please have a look. Best regards 

Reimar

**Comment by brunobord** [comment]
fixed, thanks a million to both of you for the good vibes!

The version 4.0.0 of `skyfield-data` has been released and pushed to PyPI. Happy upgrading!

https://pypi.org/project/skyfield-data/4.0.0/

Also, I'd love to hear about your usage of Skyfield and Skyfield data, that means a lot to me to know that my modest contribution is worth something.
