### ISSUE TITLE
RuntimeWarning: The file finals2000A.all has expired

### ISSUE THREAD

**Issue by thierry-FreeBSD** [brunobord/skyfield-data#29]
Hello,
I'm running the latest release, i.e. "4.0.0 - The Curse of February 2022", but it emits the following warning:
```
/usr/local/lib/python3.9/site-packages/skyfield_data/expirations.py:49: RuntimeWarning: The file finals2000A.all has expired. Please upgrade your version of `skyfield-data` or expect computation errors
  warnings.warn(message, RuntimeWarning)
```

**Comment by ReimarBauer** [comment]
It has a lifetime of a year https://pypi.org/project/skyfield-data/ expires after 2023-04-09

**Comment by Deuchnord** [comment]
Is this package still maintained? If not, it would be great if it could be taken over to not let it die :/

**Comment by brunobord** [comment]
hello there ; sorry for the late reply... this project needs more care ; I'll try to fix it as soon as I can.

**Comment by brunobord** [comment]
skyfield-data v5.0.0 has been released and published, thanks to the great work of @ReimarBauer.

Happy upgrading!

References:


* https://pypi.org/project/skyfield-data/
* https://pypi.org/project/skyfield-data/5.0.0/
* https://github.com/brunobord/skyfield-data/releases/tag/5.0.0
