### ISSUE TITLE
`test_current_expiration_date` fails due to expiration on 2024-06-16

### ISSUE THREAD

**Issue by matrss** [brunobord/skyfield-data#36]

**Comment by ReimarBauer** [comment]
Dear @brunobord 

@matrss refers to a test we have in our MSS CI process for checking the expiration, https://github.com/Open-MSS/MSS/issues/2406

We had a similiar problem also last year, see
https://github.com/brunobord/skyfield-data/issues/29

Could you do that fix again or let us know if we can help

best regards
Reimar

**Comment by matrss** [comment]
Actually, I was referring to a test of skyfield-data that was failing (while packaging it for nixpkgs), but there is another test in MSS now that is also failing for the same reason.

**Comment by ololyp** [comment]
Hello,
Not sure if it will fully address this issue, I've proposed PR #37 to update data file and expiration date in this repository.
This is my first contribution to a public repository, hope I've done nothing wrong for this PR.

**Comment by ReimarBauer** [comment]
@ololyp thx for helping, I was also working on it and remembered not directly the `make download.` So I was a bit unsure on the xml date. Yours was a second opinion that it is the correct date. And make download was  doing correctly ;)
I fixed the testing issue too.

**Comment by ReimarBauer** [comment]
When it is uploaded to pypi the feedstock on conda-forge will update automatically. Or I do merge it there.

**Comment by brunobord** [comment]
I feel so dumb... I seem to be unable to upload the latest skyfield-data release. I'll keep on struggling, but I can't see the solution right now :(

**Comment by brunobord** [comment]
FINALLY! https://pypi.org/project/skyfield-data/6.0.0/

Happy upgrading!

**Comment by ReimarBauer** [comment]
When touching this again, the table with the expiration dates needs a change too.

https://pypi.org/project/skyfield-data/
