### ISSUE TITLE
ValueError: year is out of range

### ISSUE THREAD

**Issue by mlroteman2** [brunobord/skyfield-data#7]
my code:
from skyfield_data import get_skyfield_data_path
from skyfield.api import Loader
load = Loader(get_skyfield_data_path(), expire=False)
planets = load('de421.bsp')  # this command won't download this file
ts = load.timescale()  # this command won't download the deltat + Leap Second files

post install / upgrade info:
sudo python3 -m pip install --upgrade skyfield
Successfully installed skyfield-1.20
sudo python3 -m pip install --upgrade skyfield skyfield-data
Successfully installed skyfield-data-1.0.0
-----------------------------------------------------------------------------------------------------------------
output when py file runs:
pi@gserver1:~/code-repository $  env /usr/bin/python3 /home/pi/.vscode-oss/extensions/ms-python.python-2020.5.78807/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher 39149 -- /home/pi/code-repository/skytest9.py 
Traceback (most recent call last):
  File "/home/pi/code-repository/skytest9.py", line 5, in <module>
    ts = load.timescale()  # this command won't download the deltat + Leap Second files
  File "/home/pi/.local/lib/python3.5/site-packages/skyfield/iokit.py", line 270, in timescale
    preds = self('deltat.preds')
  File "/home/pi/.local/lib/python3.5/site-packages/skyfield/iokit.py", line 151, in __call__
    expiration_date, data = parser(f)
  File "/home/pi/.local/lib/python3.5/site-packages/skyfield/iokit.py", line 347, in parse_deltat_preds
    expiration_date = date(year[0] + 2, month[0], 1)
ValueError: year is out of range
pi@gserver1:~/code-repository $ 
-------------------------------------------------------------------------------------
did I do something wrong? I installed the skyfield data trying to get past the time server issue with skyfield. Thanks!

**Comment by brunobord** [comment]
I'll try to investigate, but could you please tell me why you're installing your `skyfield` and `skyfield-data` packages as root?
and at the same time, you're running the `"skytest9.py"` script by providing a weird path (`/home/pi/.vscode-oss/extensions/ms-python.python-2020.5.78807/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher 39149 --`)...

Please try this, for example:

``/usr/bin/python3 /home/pi/code-repository/skytest9.py``

And, to isolate the issue, could you please try to run the installation and the python test script inside a virtualenv?

**Comment by brunobord** [comment]
I've run successfully the following:

```sh
$ cd /tmp
$ virtualenv venv --python=python3.5  # this is apparently the version you're using
$ source venv/bin/activate
$ python -m pip install skyfield skyfield-data
$ python skytest.py
SPICE kernel file 'de421.bsp' has 15 segments
  JD 2414864.50 - JD 2471184.50  (1899-07-28 through 2053-10-08)
      0 -> 1    SOLAR SYSTEM BARYCENTER -> MERCURY BARYCENTER
      0 -> 2    SOLAR SYSTEM BARYCENTER -> VENUS BARYCENTER
      0 -> 3    SOLAR SYSTEM BARYCENTER -> EARTH BARYCENTER
      0 -> 4    SOLAR SYSTEM BARYCENTER -> MARS BARYCENTER
      0 -> 5    SOLAR SYSTEM BARYCENTER -> JUPITER BARYCENTER
      0 -> 6    SOLAR SYSTEM BARYCENTER -> SATURN BARYCENTER
      0 -> 7    SOLAR SYSTEM BARYCENTER -> URANUS BARYCENTER
      0 -> 8    SOLAR SYSTEM BARYCENTER -> NEPTUNE BARYCENTER
      0 -> 9    SOLAR SYSTEM BARYCENTER -> PLUTO BARYCENTER
      0 -> 10   SOLAR SYSTEM BARYCENTER -> SUN
      3 -> 301  EARTH BARYCENTER -> MOON
      3 -> 399  EARTH BARYCENTER -> EARTH
      1 -> 199  MERCURY BARYCENTER -> MERCURY
      2 -> 299  VENUS BARYCENTER -> VENUS
      4 -> 499  MARS BARYCENTER -> MARS
<skyfield.timelib.Timescale object at 0x7f210ff0b198>
```

contents of my `skytest.py`:

```python
from skyfield_data import get_skyfield_data_path
from skyfield.api import Loader
load = Loader(get_skyfield_data_path(), expire=False)
planets = load('de421.bsp') # this command won't download this file
ts = load.timescale() # this command won't download the deltat + Leap Second files

print(planets)
print(ts)
```

**Comment by mlroteman2** [comment]
It's on a raspberry pi 3 that is only local network. Using skyfield to pull
sun and moon position until it stopped working.

**Comment by mlroteman2** [comment]
The wwird path is because im coding with a port of visual studio for
raspbian.

**Comment by brunobord** [comment]
> It's on a raspberry pi 3 that is only local network

I... I don't get why this raspberry pi is only on your local network.

I'm not sure, but my guess is that the latest skyfield package require **other packages** (dependencies) to be installed. If this rasberrypi can't access the Internet, it won't be able to download packages... how are `skyfield-*` packages available on your rpi3 if you don't have access to the Internet?

I highly recommend you to try out skyfield and skyfield-data **inside a virtualenv** on your regular computer first, before trying on raspberry pi. Virtualenvs are the real go-to way to install python packages in a disposable and isolated environment.

It's really not recommended to make a `sudo install`, even on a raspberry pi ; you may mess up your system by installing packages that would override your system libraries.

**Comment by mlroteman2** [comment]
Thanks for your help!

**Comment by brunobord** [comment]
well... did it work?

**Comment by mlroteman2** [comment]
Yes good to go thanks.

**Comment by brunobord** [comment]
ah! I'm glad, then. Happy skyfielding!
